ports:
  - port: 5173
    onOpen: open-preview

tasks:
  - init: pnpm install
    command: pnpm dev

vscode:
  extensions:
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss
    - svelte.svelte-vscode
